export PATH := $(GOPATH)/bin:$(PATH)
export GO111MODULE=on
LDFLAGS := -s -w
BIN_PREFIX := hexo_deploy_agent

os-archs=darwin:amd64 darwin:arm64 linux:amd64 linux:arm64 windows:amd64

all: build

build: app

app:
	@$(foreach n, $(os-archs),\
		os=$(shell echo "$(n)" | cut -d : -f 1);\
		arch=$(shell echo "$(n)" | cut -d : -f 2);\
		target_suffix=$${os}_$${arch};\
		echo "Build $${os}-$${arch}...";\
		env CGO_ENABLED=0 GOOS=$${os} GOARCH=$${arch}  go build -trimpath -ldflags "$(LDFLAGS)" -o ./release/$(BIN_PREFIX)_$${target_suffix} ./cmd;\
		echo "Build $${os}-$${arch} done";\
	)
	@mv ./release/$(BIN_PREFIX)_windows_amd64 ./release/$(BIN_PREFIX)_windows_amd64.exe